### ISSUE TITLE
校章の画像のライセンスについて

### ISSUE THREAD

**Issue by kadoshita** [codeforkosen/kosen-opendata#17]
高専かるたの投稿を見て、こちらのリポジトリにたどり着きました。
様々なデータをオープンデータとして公開してくださり、高専の一卒業生として嬉しく思います。

一点気になったことがあるため、質問させてください。
こちらのリポジトリはMITライセンスで公開されていますが、各高専の校章の画像についてもライセンスはMITでしょうか?
MITライセンスでは商用の利用や改変が許可されているため、校章の画像を商用利用したり改変することもライセンス上は可能である認識です。
もし、適切に許諾を得た上でMITライセンスで公開されているということでしたら、こちらの質問はご放念いただければと思います。
画像に関するライセンスが明記されていれば、より安心してデータを利用できるかと思いますので、ご確認いただけると嬉しいです。

**Comment by taisukef** [comment]
ご質問ありがとうございます！
校章は各学校の著作物です。こちら追記しておきます。

**Comment by kadoshita** [comment]
ありがとうございます!
校章はMITライセンスの適用範囲外である旨、承知いたしました!
