### ISSUE TITLE
data/school_emblem のファイル名の命名規則が不明 かつ ファイル名と高専名の対応が明示されていない

### ISSUE THREAD

**Issue by daiking1756** [codeforkosen/kosen-opendata#5]
# 概要
- 例えば、 https://github.com/codeforkosen/kosen-opendata/blob/main/data/school_emblem/school_emblem_1/20.jpg は石川高専の校章であるが、ファイルパス(`data/school_emblem/school_emblem_1/20.jpg`)からはこれが石川高専の校章であることが特定できない。
  - https://github.com/codeforkosen/kosen-opendata/blob/main/data/school_emblem/school_emblem_1.jpg の縦横の配置でファイル名が設定されているようにも見えるが、一部異なる命名もある。
- また、対応表のようなファイルも存在しない。

# 背景

- 各高専の校章とその由来(石川高専の場合は https://www.ishikawa-nct.ac.jp/outline/mark.html )を使ったプロダクトを作成しようとしていました。
- そんなときに、 https://fukuno.jig.jp/3766 の記事経由でこのrepository内に画像ファイルがオープンデータとして公開されていることを知りました。（オープンデータ化ありがとうございます！）
- ただ、現状では件名の問題があるため、使いにくい状態になっています。
- そこで本issueを作成しております。

**Comment by taisukef** [comment]
校章と高専との対応表、こちらです
https://github.com/codeforkosen/kosen-opendata/blob/main/data/kosen.csv

**Comment by daiking1756** [comment]
ありがとうございます。見落としておりました。こちらは対応表があるということだったので、closeします。
